add doc for Lab/Badge
jpmorganchase/uitk pull request #194
Opened 2022-06-16 07:32 UTC by LeoLYW12138

Add doc page for Lab/Badge component as requested by https://github.com/jpmorganchase/uitk/issues/161

2022-06-16 14:25 UTC, libertymayc commented on packages/lab/stories/badge.doc.stories.mdx
> +The Badge component provides a small status descriptor for UI elements. It is a small circle containing a number or a few characters that typically appears in one of the corners of the UI element.
Change wording to "A Badge is numeric annotation that indicates the number of outstanding items that need to be addressed. It appears on the top-right of an element, usually an icon. The badge can accommodate values of up to four digits in length."

2022-06-16 14:39 UTC, libertymayc commented on packages/lab/stories/Badge.stories.newapp-badge.css
> +.uitk-success.uitk-newapp {
we should provide these as a className to the badge ("uitkBadge-success" on the component) and then have .uitk-newapp .uitkBadge-success {  
  --uitkBadge-content-icon-color: var(--uitk-status-success-foreground);
  --uitkBadge-content-text-color: var(--uitk-color-white);
}
and same for error! :)

2022-06-16 14:42 UTC, libertymayc commented on packages/lab/stories/badge.stories.tsx
> +    <ToolkitProvider theme={["success", 'newapp']}>
we need to keep "light" or "dark" in the theme to get the rest of the styles (in storybook, we luckily have them coming from higher up)
then, let's add 2 Badge's to both light and dark, one with className 'success' and one with 'error'! :)

2022-06-16 14:44 UTC, libertymayc requested changes
Changes requested in comments

2022-06-16 15:45 UTC, LeoLYW12138 commented
Thank you for your review! Sorry for any silly mistakes as I'm a first-time contributor.

2022-06-16 16:50 UTC, LeoLYW12138 commented
I think I did something wrong, suddenly there are merge conflicts on my branch. Is this normal?

2022-06-16 16:55 UTC, libertymayc commented
> I think I did something wrong, suddenly there are merge conflicts on my branch. Is this normal?

You just need to rebase on the main branch, as there have been some changes today :)

2022-06-20 07:27 UTC, origami-z commented
@LeoLYW12138 Thanks for the contribution. In case the CLA process is not clear for you (the label I added)

We requrie all contributors to JPMC projects to complete our Contribution Licence Agreement (CLA). You can sign as an individual or as representing your company. You only need to do this once and it covers all current and future projects managed under our GitHub organization.

The contribution agreement can be found here [JPMC CLA](https://github.com/jpmorganchase/.github/blob/main/Contribution%20License%20Agreement%20(CLA)%20JPMC%202022.pdf), follow the instructions to complete and return to [opensource_cla@jpmorgan.com](mailto:opensource_cla@jpmorgan.com)

2022-06-20 07:36 UTC, LeoLYW12138 commented
Sorry for the inconvenience but I have signed the CLA and returned to opensource_cla@jpmorgan.com through email on Friday noon GMT+8. However, there is no response or further notice.

2022-06-20 07:38 UTC, origami-z commented
I will chase up and get this merged ASAP. Thank you for the patience. 👍

2022-06-22 08:33 UTC, origami-z commented
CLA is handled by a different team. I have chased up again.

2022-06-22 14:20 UTC, origami-z approved these changes

2022-06-22 16:28 UTC, origami-z approved these changes

2022-06-22 16:31 UTC, merged