Add documentation for layer and deck layout components
jpmorganchase/uitk pull request #305
Opened 2022-08-10 10:07 UTC by JoanaMMoreira

2022-08-11 13:24 UTC, sion-docs requested changes
- Check sentence case is used for all headings i.ie. only first letter is capitalised
 - When referring to the Layer layout, use capital L for Layer

2022-08-11 15:17 UTC, JoanaMMoreira commented
> * Check sentence case is used for all headings i.ie. only first letter is capitalised
> * When referring to the Layer layout, use capital L for Layer

Thanks Sion, I've made some tweaks. Let me know your thoughts :)

2022-08-11 16:32 UTC, sion-docs approved these changes
Thanks, great

2022-08-12 08:17 UTC, libertymayc approved these changes

2022-08-12 08:20 UTC, ImmanuelBaskaran approved these changes

2022-08-12 08:21 UTC, merged