Make button non polymorphic
jpmorganchase/uitk pull request #341
Opened 2022-08-23 09:00 UTC by ImmanuelBaskaran

2022-08-23 12:01 UTC, origami-z commented
Marking draft before ready for review

2022-08-25 11:49 UTC, joshwooding commented on packages/core/src/button/Button.tsx
> +  onBlur?: (evt: FocusEvent<HTMLButtonElement>) => void;
Do we still need these?

2022-08-25 11:51 UTC, joshwooding commented on packages/core/src/button/Button.tsx
> +export type ButtonProps = ButtonBaseProps &
This could be simpler now and follow our usual patten of being in the interface?

2022-08-25 11:51 UTC, joshwooding commented on packages/core/src/button/Button.tsx
> +  ref?: Ref<HTMLButtonElement>
```suggestion
  ref?: ForwardedRef<HTMLButtonElement>
```

2022-08-25 11:52 UTC, joshwooding commented on packages/core/src/button/Button.tsx
> +  const handleKeyUp = (event: KeyboardEvent<HTMLButtonElement>) => {
If this active logic is the same between components could we create a useActiveStyle or something hook?

2022-08-25 11:53 UTC, joshwooding commented on packages/core/src/button/Button.tsx
> +  const role = roleProp !== undefined ? roleProp : "button";
This logic isn't correct, also we shouldn't need it anymore

2022-08-25 11:53 UTC, joshwooding commented on packages/core/src/button/DivButton.tsx
> +  onBlur?: (evt: FocusEvent<HTMLDivElement>) => void;
Same comments as the other file

2022-08-25 11:54 UTC, joshwooding commented on packages/core/src/button/Button.tsx
> +  const handleKeyUp = (event: KeyboardEvent<HTMLButtonElement>) => {
We could also do a useButton hook and include focusWhenDisabled

2022-08-25 11:55 UTC, joshwooding commented on packages/lab/src/dropdown/DropdownButton.tsx
>        // We don't want the 'button' tag to be shown in the DOM to trigger some accessibility testing
This comment isn't valid now. We could either remove it or put it above the return

2022-08-25 11:56 UTC, joshwooding commented on packages/lab/src/toolbar/ToolbarButton.tsx
> +export const ToolbarButton = forwardRef(function ToolbarButton(
I've just noticed, is there a benefit to typing the parameters specifically instead of using the forwardRef's generics?

2022-08-25 11:57 UTC, joshwooding requested changes
See feedback

2022-08-25 20:15 UTC, joshwooding commented on packages/core/src/button/DivButton.tsx
> +    const role = roleProp !== undefined ? roleProp : "button";
We should probably inline this and let role be spread on div.

2022-09-01 13:50 UTC, joshwooding requested changes
The docs for Button will now need to be updated

2022-09-08 16:05 UTC, ImmanuelBaskaran commented
This pull request contains temporary changes to Pill to accomodate moving the DivButton into labs as an internal component, these changes will be reverted when @joshwooding refactors Pill very soon

2022-09-12 12:12 UTC, joshwooding commented on .changeset/yellow-tables-worry.md
> +Removed polymorphic types from Button
Can we expand on this please. Only saying the types are being removed is a bit misleading.

2022-09-12 12:13 UTC, joshwooding commented on packages/lab/stories/toolbar.qa.stories.tsx
> +        <ToolbarButton itemID="exportButton" overflowLabel="Export">
Was this change intentional?

2022-09-12 12:21 UTC, joshwooding commented on packages/lab/stories/toolbar.qa.stories.tsx
> +        <ToolbarButton itemID="exportButton" overflowLabel="Export">
Just looked through the code. This was more probably supposed to be id="" instead of itemId or itemID

2022-09-12 13:14 UTC, joshwooding approved these changes

2022-09-12 13:57 UTC, merged