Update layout docs to reflect changes made to the template
jpmorganchase/uitk pull request #419
Opened 2022-09-15 16:04 UTC by JoanaMMoreira

2022-09-26 08:00 UTC, sion-docs approved these changes

2022-09-27 21:54 UTC, joshwooding requested changes

2022-09-27 21:54 UTC, joshwooding commented on packages/core/stories/help-and-support.doc.mdx
> +Please check the issues section of the github repository for any development or design related questions or issues you have.
```suggestion
Please check the issues section of the GitHub repository for any development or design related questions or issues you have.
```

2022-09-27 21:54 UTC, joshwooding commented on packages/core/stories/layout/flex-layout.doc.stories.mdx
> +**ResponsiveProp** refers to a prop than take either multiple values (one per breakpoint) or a single value that would take effect across all different screen sizes.
```suggestion
**ResponsiveProp** refers to a prop that takes either multiple values (one per breakpoint) or a single value that would take effect across all different screen sizes.
```
?

2022-10-03 09:04 UTC, sion-docs submitted a review, later dismissed

2022-10-06 09:25 UTC, Fercas123 submitted a review, later dismissed

2022-10-06 09:41 UTC, Fercas123 commented on packages/core/stories/layout/flex-layout.doc.stories.mdx
> -**ResponsiveProp** refers to a prop than take either multiple values (one per breakpoint) or a single value that would take effect across all different screen sizes.
should be ` that takes`

2022-10-06 09:42 UTC, Fercas123 commented on packages/core/stories/layout/grid-layout.doc.stories.mdx
> -**ResponsiveProp** refers to a prop than take either multiple values (one per breakpoint) or a single value that would take effect across all different screen sizes.
I think this is happening in more places, might be worth checking all the example's text

2022-10-06 10:59 UTC, JoanaMMoreira commented
> sorry, just saw this from Josh's comments, there is also the lowecase github one but i couldn't find it

I think that was the only place we had it as far as I can tell

2022-10-06 11:34 UTC, sion-docs submitted a review, later dismissed

2022-10-06 12:50 UTC, joshwooding requested changes

2022-10-06 12:50 UTC, joshwooding commented on packages/core/stories/layout/border-layout.doc.stories.mdx
> +You want a customised layout that you can control in both row and column dimensions. In this case we recommend you having a look at [Grid layout](?path=/docs/documentation-core-layout-gridlayout--pag
```suggestion
You want a customized layout that you can control in both row and column dimensions. In this case we recommend you having a look at [Grid layout](?path=/docs/documentation-core-layout-gridlayout--page).
```

2022-10-06 12:50 UTC, joshwooding commented on packages/core/stories/layout/grid-layout.doc.stories.mdx
>  A grid item allows more complex controls to the default behaviour of a grid child, like defining how many rows or columns will it span trough and it's alignment
```suggestion
A grid item allows more complex controls to the default behavior of a grid child, like defining how many rows or columns will it span trough and it's alignment
```

2022-10-06 12:50 UTC, joshwooding commented on packages/core/stories/layout/grid-layout.doc.stories.mdx
>  The grid supports the use of responsive props, so you can define different behaviours based on viewport size.
```suggestion
The grid supports the use of responsive props, so you can define different behaviors based on viewport size.
```

2022-10-06 12:50 UTC, joshwooding commented on packages/core/stories/layout/grid-layout.doc.stories.mdx
>  All grid props are responsive, and their values can be individually customised per breakpoint.
```suggestion
All grid props are responsive, and their values can be individually customized per breakpoint.  
```

2022-10-06 12:50 UTC, joshwooding commented on packages/core/stories/layout/layer-layout.doc.stories.mdx
> +The component will be displayed in the center position by default but you can customise this via the `position` prop as per the following examples.
```suggestion
The component will be displayed in the center position by default but you can customize this via the `position` prop as per the following examples.
```

2022-10-06 12:50 UTC, joshwooding commented on packages/core/stories/layout/layer-layout.doc.stories.mdx
> +You can customise or disable the animations using the `prefers-reduced-motion` CSS media feature.
```suggestion
You can customize or disable the animations using the `prefers-reduced-motion` CSS media feature.
```

2022-10-06 12:50 UTC, joshwooding commented on packages/core/stories/layout/parent-child-layout.doc.stories.mdx
> +You can customise or disable the animations using the `prefers-reduced-motion` CSS media feature.
```suggestion
You can customize or disable the animations using the `prefers-reduced-motion` CSS media feature.
```

2022-10-07 10:11 UTC, Fercas123 approved these changes

2022-10-07 10:12 UTC, sion-docs approved these changes

2022-10-07 10:30 UTC, sion-docs commented
I have noticed some inconsistency around sentence style in the headings, the following need to be updated:
- Border layout
- Flow layout
- ParentChild layout
- Stack layout

2022-10-07 13:48 UTC, merged