Make button's default type "button" instead of submit
jpmorganchase/uitk pull request #466
Opened 2022-10-03 10:22 UTC by ImmanuelBaskaran

This pull request fixes issue #461, by setting the attribute `type` to "button".

2022-10-03 11:00 UTC, joshwooding commented on packages/core/src/button/Button.tsx
> +      type: typeProp,
```suggestion
      type = "button",
```
There's no point renaming the prop here and we should try and keep defaults with the props.

2022-10-03 13:38 UTC, origami-z requested changes
Need some test

2022-10-03 16:09 UTC, ZarkoPernar approved these changes

2022-10-04 11:37 UTC, joshwooding submitted a review, later dismissed

2022-10-11 08:16 UTC, joshwooding approved these changes

2022-10-11 08:18 UTC, merged