update stories for flex and stack
jpmorganchase/uitk pull request #516
Opened 2022-10-13 15:25 UTC by Fercas123

delete unused example for stack layout and turn on flex wrap by default for example's accessibility

2022-10-13 18:25 UTC, joshwooding commented on packages/core/src/__tests__/__e2e__/layout/Flex.cy.tsx
>        cy.mount(<DefaultFlexLayout wrap />);
This line needs to be updated.

2022-10-14 12:20 UTC, joshwooding requested changes

2022-10-14 12:20 UTC, joshwooding commented on packages/core/stories/layout/split-layout.stories.tsx
> +    <FlexContent classname="layout-content-right">Item 4</FlexContent>
We should fix the className capitalization on FlexContent instead

2022-10-14 13:01 UTC, joshwooding submitted a review, later dismissed

2022-10-14 13:10 UTC, joshwooding commented on packages/core/src/layout/SplitLayout/SplitLayout.tsx
> +        align={align}
Is it worth calling out this bug fix?

2022-10-14 15:05 UTC, joshwooding commented on .changeset/cold-balloons-hug.md
> +"@jpmorganchase/uitk-core": minor
```suggestion
"@jpmorganchase/uitk-core": patch
```

2022-10-18 13:40 UTC, ZarkoPernar approved these changes

2022-10-18 17:12 UTC, joshwooding approved these changes

2022-10-18 18:30 UTC, merged