[WIP] button docs
jpmorganchase/uitk pull request #711
Opened 2022-11-24 09:19 UTC by Fercas123

2022-11-28 16:42 UTC, joshwooding commented on packages/core/src/pill/internal/DivButton.tsx
> +    //
?

2022-11-28 16:45 UTC, joshwooding commented on packages/core/stories/layout/stack-layout.stories.tsx
> -import { Dropdown } from "@jpmorganchase/uitk-lab";
Nit: Change doesn't seem relevant to Button

2022-11-28 16:45 UTC, joshwooding commented on packages/lab/src/__tests__/__e2e__/contact-details/ContactDetails.accessibility.cy.tsx
> +          cy.findByText(label).should("have.focus");
👍🏽

2022-11-29 10:07 UTC, sion-docs approved these changes

2022-11-29 14:36 UTC, joshwooding commented on packages/core/src/button/useButton.ts
> +    "aria-disabled": focusableWhenDisabled,
Not sure this is right, I would expect aria-disabled to be on when disabled and focusWhenDisabled is true

2022-11-29 15:01 UTC, joshwooding requested changes
See comment above, sorry!

2022-11-29 15:01 UTC, joshwooding commented on packages/core/src/button/useButton.ts
> +    "aria-disabled": disabled && focusableWhenDisabled,
```suggestion
    "aria-disabled": disabled && focusableWhenDisabled ? true : undefined,
```
Sorry, I think this should be this. This should prevent aria-disabled being applied when the button isn't disabled

2022-11-29 15:40 UTC, joshwooding submitted a review, later dismissed

2022-11-29 17:18 UTC, joshwooding commented on .changeset/warm-mangos-brake.md
> +- fix `aria-disabled` to only show when not redundant.
```suggestion
- Fix `aria-disabled` to only show when not redundant.
```

2022-11-29 17:19 UTC, joshwooding commented on .changeset/warm-mangos-brake.md
> +- Removed of `DivButton`. for lab components that used `DivButton`, it's been replaced by a `Button` (`Tab` and `Dropdown`) or a custom internal `div` (`Pill`).
```suggestion
- Removed `DivButton`. For lab components that used `DivButton`, it's been replaced by a `Button` (`Tab` and `Dropdown`) or a custom internal `div` (`Pill`).
```

2022-11-29 17:27 UTC, merged