[WIP] Use real instead of fake focus on table cells
jpmorganchase/uitk pull request #741
Opened 2022-11-29 14:06 UTC by ZarkoPernar

2022-11-29 17:24 UTC, joshwooding commented on packages/grid/src/BaseCell.css
> +.uitkGridBaseCell:focus .uitkGridBaseCell-valueContainer {
You probably want focus-visible here

2022-11-30 11:27 UTC, ZarkoPernar commented on packages/grid/src/BaseCell.css
> +.uitkGridBaseCell:focus .uitkGridBaseCell-valueContainer {
Good idea

2022-12-01 17:13 UTC, ararus approved these changes

2022-12-01 17:34 UTC, ararus submitted a review, later dismissed

2022-12-01 17:41 UTC, joshwooding requested changes
We need to add a changeset

2022-12-02 11:10 UTC, ararus commented
> 

Changeset added

2022-12-02 11:21 UTC, ararus approved these changes

2022-12-02 22:30 UTC, joshwooding approved these changes

2022-12-02 22:32 UTC, merged