Text alignment and global attributes
jpmorganchase/uitk pull request #788
Opened 2022-12-05 16:21 UTC by libertymayc

2022-12-05 16:22 UTC, libertymayc commented on packages/theme/css/global.css
> + .uitk-theme {
@joshwooding this came up in a 101, but would be good to further discuss this or get your opinion

2022-12-05 16:32 UTC, joshwooding requested changes

2022-12-05 16:32 UTC, joshwooding commented on .changeset/neat-impalas-sort.md
> +Remoce text background on default and hover state tokens
```suggestion
Remove text background on default and hover state tokens
```

2022-12-05 16:32 UTC, joshwooding commented on .changeset/neat-impalas-sort.md
> +Remove base 1.3 line height, replace with appropriate line height variant throughout code
```suggestion
Remove base 1.3 line height, and replace with appropriate line height variant throughout the code
```

2022-12-05 16:37 UTC, joshwooding approved these changes

2022-12-05 17:02 UTC, joshwooding commented
There are some minor line-height changes in the chromatic changes I would like a designer to look at

2022-12-07 10:47 UTC, joshwooding approved these changes

2022-12-07 10:47 UTC, merged