Changes in prep for layouts release
jpmorganchase/uitk pull request #816
Opened 2022-12-07 15:29 UTC by Fercas123

Scope of components to release: BorderLayout, FlexLayout, FlowLayout, StackLayout.

Changes in this PR:
- Removed separators from `SplitLayout`.
- Fix types for `FlowLayout`
- Remove examples that used Lab components. Removed from docs: `FlexLayout`, `FlowLayout`, `StackLayout`.
- Move examples that are using labs and are part of out of scope components out of in scope components.
TO DO: 
- Agree/Change name for border items.

2022-12-09 14:51 UTC, sion-docs approved these changes

2022-12-09 15:30 UTC, Fercas123 commented on .changeset/beige-ravens-clap.md
> +Fix `FlowLayout` types and remove separators prop from `SplitLayout`
```suggestion
- Fix `FlowLayout` types
- Remove separators prop from `SplitLayout`
- Rename BorderItem positions to follow border layout conventions
```

2022-12-09 17:27 UTC, joshwooding requested changes
BorderLayout docs still need to be updated with the renamed positions

2022-12-12 14:43 UTC, joshwooding commented on packages/core/stories/layout/border-layout.stories.tsx
> +          <p>Left</p>
```suggestion
          <p>West</p>
```

2022-12-12 14:44 UTC, joshwooding commented on packages/core/stories/layout/border-layout.stories.tsx
> +          <p>Main section</p>
```suggestion
          <p>Center</p>
```

2022-12-12 14:44 UTC, joshwooding commented on packages/core/stories/layout/border-layout.stories.tsx
> +          <p>Right</p>
```suggestion
          <p>East</p>
```

2022-12-12 14:44 UTC, joshwooding commented on packages/core/stories/layout/border-layout.stories.tsx
> +          <p>Bottom</p>
```suggestion
          <p>South</p>
```

2022-12-12 14:44 UTC, joshwooding commented on packages/core/stories/layout/border-layout.stories.tsx
> +          <p>Top</p>
```suggestion
          <p>North</p>
```

2022-12-12 14:44 UTC, joshwooding commented on packages/core/stories/layout/border-layout.stories.tsx
> +          <p>Bottom</p>
```suggestion
          <p>South</p>
```

2022-12-12 14:44 UTC, joshwooding commented on packages/core/stories/layout/border-layout.stories.tsx
> +          <p>Right</p>
```suggestion
          <p>East</p>
```

2022-12-12 14:45 UTC, joshwooding commented on packages/core/stories/layout/border-layout.stories.tsx
> +          <p>Main section</p>
```suggestion
          <p>Center</p>
```

2022-12-12 14:45 UTC, joshwooding commented on packages/core/stories/layout/border-layout.stories.tsx
> +          <p>Left</p>
```suggestion
          <p>West</p>
```

2022-12-12 14:46 UTC, joshwooding commented on packages/core/stories/layout/border-layout.stories.tsx
> +          <p>Bottom</p>
```suggestion
          <p>South</p>
```

2022-12-12 14:46 UTC, joshwooding commented on packages/core/stories/layout/border-layout.stories.tsx
> +          <p>Right</p>
```suggestion
          <p>East</p>
```

2022-12-12 14:46 UTC, joshwooding commented on packages/core/stories/layout/border-layout.stories.tsx
> +          <p>Top</p>
```suggestion
          <p>North</p>
```

2022-12-12 14:47 UTC, joshwooding commented on packages/core/stories/layout/border-layout.stories.tsx
> +          <p>Bottom</p>
```suggestion
          <p>South</p>
```

2022-12-12 14:47 UTC, joshwooding commented on packages/core/stories/layout/border-layout.stories.tsx
> +          <p>Left</p>
```suggestion
          <p>West</p>
```

2022-12-12 14:47 UTC, joshwooding commented on packages/core/stories/layout/border-layout.stories.tsx
> +          <p>Top</p>
```suggestion
          <p>North</p>
```

2022-12-12 14:47 UTC, joshwooding commented on packages/core/stories/layout/border-layout.stories.tsx
> +          <p>Bottom</p>
```suggestion
          <p>South</p>
```

2022-12-12 14:47 UTC, joshwooding commented on packages/core/stories/layout/border-layout.stories.tsx
> +          <p>Right</p>
```suggestion
          <p>East</p>
```

2022-12-12 14:49 UTC, joshwooding commented on packages/core/stories/layout/border-layout.stories.tsx
> +          <p>Left</p>
```suggestion
          <p>West</p>
```

2022-12-12 14:49 UTC, joshwooding commented on packages/core/stories/layout/border-layout.stories.tsx
> +          <p>Top</p>
```suggestion
          <p>North</p>
```

2022-12-13 09:42 UTC, joshwooding commented on packages/core/stories/layout/border-item.stories.tsx
> +        <p>Header</p>
```suggestion
        <p>North</p>
```

2022-12-13 09:42 UTC, joshwooding commented on packages/core/stories/layout/border-item.stories.tsx
> +        <p>Main</p>
```suggestion
        <p>Center</p>
```

2022-12-13 09:42 UTC, joshwooding commented on packages/core/stories/layout/border-item.stories.tsx
> +        <p>Right</p>
```suggestion
        <p>East</p>
```

2022-12-13 09:42 UTC, joshwooding commented on packages/core/stories/layout/border-item.stories.tsx
> +        <p>Bottom</p>
```suggestion
        <p>South</p>
```

2022-12-13 09:58 UTC, joshwooding approved these changes

2022-12-13 10:39 UTC, merged