Updates to Scrim styling
jpmorganchase/uitk pull request #831
Opened 2022-12-08 12:12 UTC by libertymayc

2022-12-08 12:19 UTC, libertymayc commented on .changeset/tasty-maps-jump.md
>  ````diff
even though this was done in that pr, should i just delete the notes about it here so its not confusing? @joshwooding

2022-12-09 10:50 UTC, joshwooding commented on packages/theme/stories/characteristics/overlayable.stories.mdx
> +- `backdrop`
```suggestion
- `Scrim`
```

2022-12-09 10:51 UTC, joshwooding commented on packages/core/src/scrim/Scrim.css
> +  background: var(--uitkScrim-background, var(--uitk-overlayable-primary-background));
```suggestion
  background: var(--uitkScrim-background, var(--uitk-overlayable-background));
```

2022-12-09 10:51 UTC, joshwooding commented on packages/core/src/scrim/Scrim.tsx
> +        [withBaseName(`containerFix`)]: enableContainerMode
```suggestion
        [withBaseName("containerFix")]: enableContainerMode
```

2022-12-09 10:55 UTC, joshwooding requested changes
See comments

2022-12-09 12:46 UTC, joshwooding approved these changes

2022-12-09 16:33 UTC, joshwooding approved these changes

2022-12-09 16:34 UTC, merged