Fix footer bugs
jpmorganchase/uitk pull request #887
Opened 2022-12-13 13:22 UTC by libertymayc

#861

2022-12-13 14:51 UTC, Fercas123 approved these changes

2022-12-13 14:51 UTC, JoanaMMoreira commented on site/src/css/custom.css
> +  --ifm-footer-padding-vertical: calc(var(--uitk-size-unit) * 1.5);
Can we just check with @shey-v if she's happy with the footer height please?

2022-12-13 15:03 UTC, james-nash requested changes
Mostly fine, just need to fix a minor linting issue

2022-12-13 15:03 UTC, james-nash commented on site/src/css/custom.css
> +
This extra blank line is what's causing the linting check to fail on CI.

(You can configure VSCode to use Prettier to auto-format your files whenever you save them. That can avoid these kinds of issues)

2022-12-13 19:59 UTC, shey-v requested changes
For the max-width: 996px breakpoint, the left and right padding is lost. We need to add this in as per the other breakpoints (16px). 

Overall, the padding still looks quite tight, let's have a call in the morning. Thanks!

2022-12-14 12:02 UTC, Fercas123 approved these changes

2022-12-14 13:12 UTC, shey-v approved these changes
Looks good. Thanks!

2022-12-14 13:16 UTC, james-nash approved these changes
I hereby give my blessing to this PR 👼

2022-12-14 14:11 UTC, merged